// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPPAvphgszrn35WM3JptOfqbTtCZsRAg4',
    appId: '1:138354201411:web:95e07ddd133f2fa53695f6',
    messagingSenderId: '138354201411',
    projectId: 'todoapp-77292',
    authDomain: 'todoapp-77292.firebaseapp.com',
    storageBucket: 'todoapp-77292.firebasestorage.app',
    measurementId: 'G-YQCYDLCQMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuJJJS9P5VNYzONoFMgPrLZZQmrxpJXrE',
    appId: '1:138354201411:android:d2b0857d25f473973695f6',
    messagingSenderId: '138354201411',
    projectId: 'todoapp-77292',
    storageBucket: 'todoapp-77292.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwDewFhPSY3b7WMpKGyv8_xaOlSWjbCXw',
    appId: '1:138354201411:ios:847d8ba4b2b756023695f6',
    messagingSenderId: '138354201411',
    projectId: 'todoapp-77292',
    storageBucket: 'todoapp-77292.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwDewFhPSY3b7WMpKGyv8_xaOlSWjbCXw',
    appId: '1:138354201411:ios:847d8ba4b2b756023695f6',
    messagingSenderId: '138354201411',
    projectId: 'todoapp-77292',
    storageBucket: 'todoapp-77292.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPPAvphgszrn35WM3JptOfqbTtCZsRAg4',
    appId: '1:138354201411:web:60eae3bf68d29c2e3695f6',
    messagingSenderId: '138354201411',
    projectId: 'todoapp-77292',
    authDomain: 'todoapp-77292.firebaseapp.com',
    storageBucket: 'todoapp-77292.firebasestorage.app',
    measurementId: 'G-BH4SMPXVQP',
  );
}
